<?php declare(strict_types=1);

use Cognesy\Events\Dispatchers\EventDispatcher;
use Cognesy\Http\Exceptions\TimeoutException;
use Cognesy\Messages\Messages;
use Cognesy\Polyglot\Inference\Config\InferenceRetryPolicy;
use Cognesy\Polyglot\Inference\Creation\InferenceRequestBuilder;
use Cognesy\Polyglot\Inference\Data\InferenceExecution;
use Cognesy\Polyglot\Inference\Data\InferenceResponse;
use Cognesy\Polyglot\Inference\Data\InferenceUsage;
use Cognesy\Polyglot\Inference\Data\PartialInferenceDelta;
use Cognesy\Polyglot\Inference\PendingInference;
use Cognesy\Polyglot\Tests\Support\FakeInferenceDriver;

/**
 * Pins the ORDERED sequence of lifecycle events, with payloads, for every path through
 * InferenceExecutionSession (instructor-eexl.10).
 *
 * The fixture was captured before the class was decomposed into collaborators and must not be
 * regenerated by that refactor. Order is the thing at risk: a decomposition can very easily
 * emit the same six events in a different sequence, or emit one twice, and every existing test
 * in the package asserts presence or count rather than full ordering.
 *
 * Values that legitimately vary run to run -- ids, durations, timestamps -- are normalised by
 * VALUE SHAPE, not by key name. Normalising by key name is how you end up with a golden test
 * that quietly stops comparing the ids nested inside the telemetry envelope.
 */
const LIFECYCLE_GOLDEN_FIXTURE = __DIR__ . '/../../Fixtures/inference-lifecycle-sequences.json';

function lifecycleNormalize(mixed $value): mixed {
    if (is_array($value)) {
        $out = [];
        foreach ($value as $k => $v) {
            $out[$k] = lifecycleNormalize($v);
        }
        return $out;
    }
    if (is_float($value)) {
        // Every float in these payloads is an elapsed-ms reading.
        return '<ms>';
    }
    if (!is_string($value)) {
        return $value;
    }
    // A composite id such as "<uuid>:usage" must normalise too, hence the optional suffix.
    if (preg_match('/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}(:.*)?$/i', $value)) {
        return '<uuid>' . ($value === '' ? '' : (strstr($value, ':') ?: ''));
    }
    if (preg_match('/^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}:\d{2}/', $value)) {
        return '<timestamp>';
    }
    return $value;
}

/**
 * @return array<int, array{event: string, data: mixed}>
 */
function lifecycleRecord(callable $scenario): array {
    $events = new EventDispatcher();
    $recorded = [];
    $events->wiretap(function (object $event) use (&$recorded): void {
        $name = (new ReflectionClass($event))->getShortName();
        if (!str_starts_with($name, 'Inference')) {
            return;
        }
        $recorded[] = [
            'event' => $name,
            'data' => lifecycleNormalize($event->data ?? []),
        ];
    });

    try {
        $scenario($events);
    } catch (\Throwable $e) {
        // The throw is part of the path being pinned -- three of the eight paths end in one,
        // and WHICH exception ends them is as much a part of the contract as the events.
        $recorded[] = ['event' => 'THROWN:' . (new ReflectionClass($e))->getShortName(), 'data' => $e->getMessage()];
    }

    return $recorded;
}

function lifecyclePending(FakeInferenceDriver $driver, EventDispatcher $events, bool $streamed, ?InferenceRetryPolicy $policy = null): PendingInference {
    $builder = (new InferenceRequestBuilder())
        ->withMessages(Messages::fromString('Say hi'))
        ->withModel('test-model')
        ->withStreaming($streamed);

    if ($policy !== null) {
        $builder = $builder->withRetryPolicy($policy);
    }

    return new PendingInference(
        execution: InferenceExecution::fromRequest($builder->create()),
        driver: $driver,
        eventDispatcher: $events,
    );
}

function lifecycleUsage(): InferenceUsage {
    return new InferenceUsage(inputTokens: 11, outputTokens: 7);
}

/**
 * The eight paths. Seven are the ones the plan enumerates; the eighth is the re-entrant one
 * that $finalizingCachedStreamViaResponse exists for.
 *
 * @return array<string, callable(EventDispatcher): mixed>
 */
function lifecycleScenarios(): array {
    return [
        'success' => fn(EventDispatcher $e) => lifecyclePending(
            new FakeInferenceDriver(onResponse: fn() => new InferenceResponse(
                content: 'hi', finishReason: 'stop', usage: lifecycleUsage(),
            )),
            $e, streamed: false,
        )->response(),

        'retry_then_success' => function (EventDispatcher $e) {
            $calls = 0;
            return lifecyclePending(
                new FakeInferenceDriver(onResponse: function () use (&$calls) {
                    if (++$calls === 1) {
                        throw new TimeoutException('upstream timeout');
                    }
                    return new InferenceResponse(content: 'hi', finishReason: 'stop', usage: lifecycleUsage());
                }),
                $e, streamed: false,
                policy: new InferenceRetryPolicy(maxAttempts: 2, baseDelayMs: 0),
            )->response();
        },

        'retry_exhausted' => fn(EventDispatcher $e) => lifecyclePending(
            new FakeInferenceDriver(onResponse: fn() => throw new TimeoutException('upstream timeout')),
            $e, streamed: false,
            policy: new InferenceRetryPolicy(maxAttempts: 2, baseDelayMs: 0),
        )->response(),

        'length_recovery' => function (EventDispatcher $e) {
            $calls = 0;
            return lifecyclePending(
                new FakeInferenceDriver(onResponse: function () use (&$calls) {
                    return (++$calls === 1)
                        ? new InferenceResponse(content: 'trunc', finishReason: 'length', usage: lifecycleUsage())
                        : new InferenceResponse(content: 'trunc done', finishReason: 'stop', usage: lifecycleUsage());
                }),
                $e, streamed: false,
                policy: new InferenceRetryPolicy(
                    maxAttempts: 1, baseDelayMs: 0, lengthRecovery: 'continue', lengthMaxAttempts: 2,
                ),
            )->response();
        },

        'content_filter' => fn(EventDispatcher $e) => lifecyclePending(
            new FakeInferenceDriver(onResponse: fn() => new InferenceResponse(
                content: '', finishReason: 'content_filter', usage: lifecycleUsage(),
            )),
            $e, streamed: false,
        )->response(),

        'stream_success' => function (EventDispatcher $e) {
            $pending = lifecyclePending(
                new FakeInferenceDriver(onStream: fn() => [
                    new PartialInferenceDelta(contentDelta: 'he'),
                    new PartialInferenceDelta(contentDelta: 'llo', finishReason: 'stop'),
                ]),
                $e, streamed: true,
            );
            return iterator_to_array($pending->stream()->responses());
        },

        // A connection dropped at handshake: the driver throws on the very first advance.
        // This path used to emit NO failure events at all, because rewind() sat outside
        // emitVisibleDeltas()'s try/catch (instructor-eexl.22). It must stay indistinguishable
        // from the after-first-delta case below -- that pair is the regression test.
        'stream_failure_before_first_delta' => function (EventDispatcher $e) {
            $pending = lifecyclePending(
                new FakeInferenceDriver(onStream: fn() => throw new TimeoutException('stream died')),
                $e, streamed: true,
                policy: new InferenceRetryPolicy(maxAttempts: 1, baseDelayMs: 0),
            );
            return iterator_to_array($pending->stream()->responses());
        },

        // The stream-failure path the plan means: the failure lands mid-iteration, inside the
        // try, so onStreamFailed fires and the session dispatches its failure events.
        'stream_failure_after_first_delta' => function (EventDispatcher $e) {
            $pending = lifecyclePending(
                new FakeInferenceDriver(onStream: function (): iterable {
                    yield new PartialInferenceDelta(contentDelta: 'he');
                    throw new TimeoutException('stream died mid-flight');
                }),
                $e, streamed: true,
                policy: new InferenceRetryPolicy(maxAttempts: 1, baseDelayMs: 0),
            );
            return iterator_to_array($pending->stream()->responses());
        },

        // Length recovery that runs out of credit. Distinct from 'length_recovery', which
        // succeeds on its second go and therefore never exercises the recovery budget at
        // all -- the driver here keeps truncating until the policy gives up.
        'length_recovery_exhausted' => function (EventDispatcher $e) {
            $calls = 0;
            return lifecyclePending(
                new FakeInferenceDriver(onResponse: function () use (&$calls) {
                    return (++$calls <= 3)
                        ? new InferenceResponse(content: 'trunc', finishReason: 'length', usage: lifecycleUsage())
                        : new InferenceResponse(content: 'done', finishReason: 'stop', usage: lifecycleUsage());
                }),
                $e, streamed: false,
                policy: new InferenceRetryPolicy(
                    maxAttempts: 1, baseDelayMs: 0, lengthRecovery: 'continue', lengthMaxAttempts: 2,
                ),
            )->response();
        },

        // The re-entrant path: a STREAMED request whose caller asks for response() without
        // ever draining deltas(). response() -> makeResponse() -> finalizeCachedStreamForResponse()
        // -> stream()->final() -> onStreamFinalized() re-enters the session. It must not
        // dispatch InferenceCompleted twice.
        'stream_response_without_draining' => fn(EventDispatcher $e) => lifecyclePending(
            new FakeInferenceDriver(onStream: fn() => [
                new PartialInferenceDelta(contentDelta: 'he'),
                new PartialInferenceDelta(contentDelta: 'llo', finishReason: 'stop'),
            ]),
            $e, streamed: true,
        )->response(),

        // The re-entrant path's failing half. response() is driving the stream, so the
        // stream's own failure callback fires while the retry loop is mid-attempt -- both
        // would otherwise terminate the same execution. The success case above cannot
        // catch a regression here: the guard is checked in two separate callbacks.
        'stream_response_without_draining_failure' => fn(EventDispatcher $e) => lifecyclePending(
            new FakeInferenceDriver(onStream: function (): iterable {
                yield new PartialInferenceDelta(contentDelta: 'he');
                throw new TimeoutException('stream died mid-flight');
            }),
            $e, streamed: true,
            policy: new InferenceRetryPolicy(maxAttempts: 1, baseDelayMs: 0),
        )->response(),
    ];
}

it('emits the pinned lifecycle event sequence for every execution path', function () {
    $golden = json_decode((string) file_get_contents(LIFECYCLE_GOLDEN_FIXTURE), true, 512, JSON_THROW_ON_ERROR);

    $actual = [];
    foreach (lifecycleScenarios() as $name => $scenario) {
        $actual[$name] = lifecycleRecord($scenario);
    }

    expect($actual)->toBe($golden);
})->group('lifecycle-sequence');

it('never dispatches InferenceCompleted more than once on any path', function () {
    // Stated separately from the fixture because it is the invariant the re-entrancy guard
    // exists to protect. A regenerated fixture could encode a double-dispatch and still pass
    // the test above; this one cannot be satisfied that way.
    foreach (lifecycleScenarios() as $name => $scenario) {
        $completed = array_filter(
            lifecycleRecord($scenario),
            fn(array $r) => $r['event'] === 'InferenceCompleted',
        );
        expect(count($completed))->toBeLessThanOrEqual(1, "path '{$name}' dispatched InferenceCompleted ".count($completed)." times");
    }
})->group('lifecycle-sequence');

it('opens every path with InferenceStarted exactly once', function () {
    foreach (lifecycleScenarios() as $name => $scenario) {
        $names = array_column(lifecycleRecord($scenario), 'event');
        $started = array_keys($names, 'InferenceStarted', true);

        expect($started)->toHaveCount(1, "path '{$name}' dispatched InferenceStarted ".count($started)." times")
            ->and($started[0])->toBe(0, "path '{$name}' did not open with InferenceStarted");
    }
})->group('lifecycle-sequence');

function lifecycleUnterminatedAttempts(array $names): int {
    $open = 0;
    $violations = [];
    foreach ($names as $event) {
        if ($event === 'InferenceAttemptStarted') {
            if ($open !== 0) {
                $violations[] = 'started an attempt while one was open';
            }
            $open = 1;
        }
        if ($event === 'InferenceAttemptSucceeded' || $event === 'InferenceAttemptFailed') {
            if ($open !== 1) {
                $violations[] = 'terminated an attempt that was not open';
            }
            $open = 0;
        }
    }
    expect($violations)->toBe([]);
    return $open;
}

it('pairs every attempt with exactly one terminal attempt event', function () {
    // AttemptStarted must be followed by exactly one of Succeeded/Failed, in order. This is
    // the property a decomposition is most likely to break while keeping the totals right.
    foreach (lifecycleScenarios() as $name => $scenario) {
        $open = lifecycleUnterminatedAttempts(array_column(lifecycleRecord($scenario), 'event'));
        expect($open)->toBe(0, "path '{$name}' left an attempt unterminated");
    }
})->group('lifecycle-sequence');

it('reports a stream failure the same way regardless of when it lands', function () {
    // instructor-eexl.22. A stream that dies on its first advance and one that dies after a
    // delta are the same event from the caller's side, and used to be wildly different: the
    // first emitted nothing at all, because rewind() -- which is what first advances the
    // driver's generator -- sat outside emitVisibleDeltas()'s try/catch.
    //
    // Stated as an invariant rather than left to the fixture on purpose. The fixture pins
    // both paths, but someone regenerating it would pin whatever the code does that day;
    // this cannot be satisfied that way.
    $scenarios = lifecycleScenarios();

    $before = array_column(lifecycleRecord($scenarios['stream_failure_before_first_delta']), 'event');
    $after = array_column(lifecycleRecord($scenarios['stream_failure_after_first_delta']), 'event');

    expect($before)->toBe($after)
        ->and($before)->toContain('InferenceAttemptFailed')
        ->and($before)->toContain('InferenceCompleted');
})->group('lifecycle-sequence');
