<?php declare(strict_types=1);

use Cognesy\Events\Dispatchers\EventDispatcher;
use Cognesy\Http\Creation\HttpClientBuilder;
use Cognesy\Http\Drivers\Mock\MockHttpDriver;
use Cognesy\Http\Drivers\Mock\MockHttpResponseFactory;
use Cognesy\Http\Telemetry\HttpRequestTelemetry;
use Cognesy\Messages\Content;
use Cognesy\Messages\ContentPart;
use Cognesy\Messages\ContentParts;
use Cognesy\Messages\Message;
use Cognesy\Messages\Messages;
use Cognesy\Messages\ToolCall;
use Cognesy\Messages\ToolCalls;
use Cognesy\Messages\ToolResult;
use Cognesy\Polyglot\Inference\Config\LLMConfig;
use Cognesy\Polyglot\Inference\Creation\BundledInferenceDrivers;
use Cognesy\Polyglot\Inference\Data\InferenceRequest;
use Cognesy\Polyglot\Inference\Data\ResponseFormat;
use Cognesy\Polyglot\Inference\Data\ToolChoice;
use Cognesy\Polyglot\Inference\Data\ToolDefinitions;
use Cognesy\Telemetry\Domain\Envelope\OperationCorrelation;

/**
 * Pins the WIRE OUTPUT of every bundled driver: the URL, headers and decoded body each one
 * produces for a fixed set of requests, plus the capabilities it reports (instructor-eexl.9).
 *
 * Landed BEFORE seventeen driver classes were replaced by declarative specs. The fixture is
 * the evidence that the replacement changed nothing, so it must not be regenerated by that
 * work. Any diff afterwards is a regression, not a rebaseline.
 *
 * The request is captured through MockHttpDriver rather than by reaching into the protected
 * toHttpRequest(), so what is pinned is what the driver would actually have sent.
 *
 * WHY SEVEN REQUESTS AND NOT ONE. The first version of this test used a single request and was
 * worse than useless: several drivers' *only* difference from plain OpenAI sits on a branch
 * that request never took, so the pin would have gone on passing while a spec refactor erased
 * them. The variants below were not guessed -- every method in the Drivers tree was
 * instrumented with an execution counter and the snapshot re-run, and each variant exists to
 * close a specific gap that measurement exposed. See the table in
 * research/plans/polyglot-improvements/measurements/eexl-9-driver-specs.md.
 *
 * Worth keeping even if the spec refactor is abandoned: nothing else in this package asserts
 * that a given provider name produces a given payload, which is the one thing every user of
 * it depends on.
 */
const DRIVER_GOLDEN_FIXTURE = __DIR__ . '/../../Fixtures/driver-golden-requests.json';

/**
 * One config for every provider, so that any difference in the captured request is
 * attributable to the driver rather than to its configuration. Every field is fixed;
 * nothing is read from the environment.
 */
function driverGoldenConfig(string $providerName): LLMConfig {
    return new LLMConfig(
        apiUrl: 'https://api.example.test/v1',
        apiKey: 'test-api-key',
        endpoint: '/chat/completions',
        queryParams: ['api-version' => '2024-01-01'],
        metadata: [
            'apiVersion' => '2024-01-01',
            'resourceName' => 'test-resource',
            'deploymentId' => 'test-deployment',
            'region' => 'us-east-1',
        ],
        model: 'test-model',
        maxTokens: 1024,
        contextLength: 8000,
        maxOutputLength: 4096,
        driver: $providerName,
        options: [],
        pricing: [],
    );
}

/** The tool definitions shared by every variant that carries tools. */
function driverGoldenTools(): ToolDefinitions {
    return ToolDefinitions::fromArray([[
        'type' => 'function',
        'function' => [
            'name' => 'get_weather',
            'description' => 'Get the weather',
            'parameters' => [
                'type' => 'object',
                'properties' => ['city' => ['type' => 'string']],
                'required' => ['city'],
                'additionalProperties' => false,
            ],
        ],
    ]]);
}

/**
 * Deliberately carries the constructs provider transforms are known to rewrite: vendor
 * extension keys, additionalProperties, nullable, an integer and an array-with-items.
 */
function driverGoldenSchema(): array {
    return [
        'type' => 'object',
        'x-title' => 'Answer',
        'x-php-class' => 'App\\Answer',
        'properties' => [
            'text' => ['type' => 'string'],
            'score' => ['type' => 'integer'],
            'tags' => ['type' => 'array', 'items' => ['type' => 'string']],
        ],
        'required' => ['text'],
        'additionalProperties' => false,
        'nullable' => false,
    ];
}

function driverGoldenPlainMessages(): Messages {
    return Messages::fromArray([
        ['role' => 'system', 'content' => 'You are terse.'],
        ['role' => 'user', 'content' => 'Say hi'],
    ]);
}

/**
 * A full round trip: a system turn, a multi-part user turn carrying an image, a second
 * consecutive user turn, an assistant turn with two tool calls, and a tool result.
 *
 * The consecutive user turns are load-bearing -- they are what makes Deepseek's
 * supportsAlternatingRoles() do anything. The image part and the tool call/result turns are
 * what reach the toNative*() branches of the Anthropic, Gemini, OpenResponses and XAI
 * message formats.
 */
function driverGoldenConversation(): Messages {
    return Messages::fromMessages([
        new Message(role: 'system', content: 'You are terse.'),
        new Message(role: 'user', content: Content::fromParts(new ContentParts(
            ContentPart::text('What is in this image?'),
            ContentPart::imageUrl('https://example.test/cat.png'),
        ))),
        new Message(role: 'user', content: 'And what is the weather in NYC?'),
        new Message(role: 'assistant', content: '', toolCalls: new ToolCalls(
            new ToolCall('get_weather', ['city' => 'NYC'], 'call_1'),
            new ToolCall('get_weather', ['city' => 'Boston'], 'call_2'),
        )),
        new Message(
            role: 'tool',
            content: '{"temp":21}',
            toolResult: ToolResult::success('{"temp":21}', 'call_1', 'get_weather'),
        ),
    ]);
}

/**
 * The seven requests the snapshot is taken over.
 *
 * @return array<string, InferenceRequest>
 */
function driverGoldenRequests(): array {
    return [
        // Tools AND a schema. Most drivers refuse both at once
        // (supportsNonTextResponseForTools), so this variant pins the DROPPING of the
        // response format as much as the tools themselves.
        'tools_and_schema' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            tools: driverGoldenTools(),
            toolChoice: ToolChoice::auto(),
            responseFormat: ResponseFormat::jsonSchema(schema: driverGoldenSchema(), name: 'answer', strict: true),
            options: ['temperature' => 0.0, 'stream' => false],
        ),

        // Same request, streamed. Pins the stream flag and the stream options Mistral and
        // Glm add for themselves.
        'tools_and_schema_streamed' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            tools: driverGoldenTools(),
            toolChoice: ToolChoice::auto(),
            responseFormat: ResponseFormat::jsonSchema(schema: driverGoldenSchema(), name: 'answer', strict: true),
            options: ['temperature' => 0.0, 'stream' => true],
        ),

        // A schema with NO tools -- the only way to reach toJsonSchemaResponseFormat() on the
        // six drivers that drop the response format whenever tools are present. Their schema
        // rendering was entirely unpinned before this variant existed.
        'schema_only' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            responseFormat: ResponseFormat::jsonSchema(schema: driverGoldenSchema(), name: 'answer', strict: true),
            options: ['temperature' => 0.0, 'stream' => false],
        ),

        // Plain JSON mode. Four drivers override toJsonObjectResponseFormat() and nothing
        // else -- for Meta it is the single line separating it from plain OpenAI. Carries
        // `thinking`, which is what Qwen rewrites to `enable_thinking`.
        'json_object' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            responseFormat: ResponseFormat::jsonObject(),
            options: ['temperature' => 0.0, 'stream' => false, 'thinking' => true],
        ),

        // Plain text mode. Reaches toTextResponseFormat() on the OpenAI base, which every
        // OpenAI-family driver inherits -- so a change there moves twenty-odd providers at
        // once, which is the exact shared-adapter failure this task has to guard against.
        'text_format' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            responseFormat: ResponseFormat::text(),
            options: ['temperature' => 0.0, 'stream' => false],
        ),

        // Tools with a REQUIRED choice and no response format. Gemini maps the choice mode
        // only on that combination: a specific choice takes a different branch, and any
        // response format short-circuits ahead of it.
        'required_choice' => new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            tools: driverGoldenTools(),
            toolChoice: ToolChoice::required(),
            options: ['temperature' => 0.0, 'stream' => false],
        ),

        // The rich conversation, with a named tool choice (Gemini's specific-choice branch) and
        // `enable_thinking`, which is what Glm rewrites to `thinking` -- the mirror image of
        // the Qwen rewrite above, and unreachable in the same request as it.
        'conversation' => new InferenceRequest(
            messages: driverGoldenConversation(),
            model: 'test-model',
            tools: driverGoldenTools(),
            toolChoice: ToolChoice::specific('get_weather'),
            options: ['temperature' => 0.0, 'stream' => false, 'enable_thinking' => true],
        ),

        // A correlated request. The telemetry wrapper is the one branch of the shared
        // toHttpRequest() that the other seven variants never take -- none of them carries a
        // correlation, so deleting the wrapper outright left every capture passing. The
        // correlation is spelled out field by field so the captured metadata is deterministic;
        // the default root correlation is derived from the request's UUID and would not be.
        'telemetry_correlated' => (new InferenceRequest(
            messages: driverGoldenPlainMessages(),
            model: 'test-model',
            options: ['temperature' => 0.0, 'stream' => false],
        ))->withTelemetryCorrelation(new OperationCorrelation(
            rootOperationId: 'golden-root-op',
            parentOperationId: 'golden-parent-op',
            sessionId: 'golden-session',
            userId: 'golden-user',
            conversationId: 'golden-conversation',
            requestId: 'golden-request',
        )),
    ];
}

/**
 * @return array{url: string, headers: array<string,mixed>, body: mixed}
 */
function driverGoldenCapture(string $providerName, InferenceRequest $request, bool $streamed): array {
    $mock = new MockHttpDriver();
    // One catch-all response: the driver only has to get far enough to send.
    $mock->addResponse(MockHttpResponseFactory::success(
        body: (string) json_encode(['choices' => [['message' => ['content' => 'hi']]]]),
    ));

    $httpClient = (new HttpClientBuilder())->withDriver($mock)->create();
    $events = new EventDispatcher();

    $driver = BundledInferenceDrivers::registry()->makeDriver(
        $providerName,
        driverGoldenConfig($providerName),
        $httpClient,
        $events,
    );

    try {
        if ($streamed) {
            // Consume enough to force the request out; the mock body is not a valid stream.
            foreach ($driver->makeStreamDeltasFor($request) as $_) {
                break;
            }
        } else {
            $driver->makeResponseFor($request);
        }
    } catch (\Throwable $e) {
        // Response parsing is not what this pins -- the request was already captured, and a
        // provider whose adapter rejects the stub body must still have produced a request.
    }

    $sent = $mock->getLastRequest();
    if ($sent === null) {
        return ['url' => 'NO REQUEST SENT', 'headers' => [], 'body' => null,
                'method' => null, 'options' => [], 'telemetry' => null];
    }

    $body = $sent->body()->toString();
    $decoded = json_decode($body, true);

    // `method`, `options` and `telemetry` are appended after `body` rather than slotted into
    // the natural order for one reason: it keeps the fixture diff that introduced them purely
    // additive, so a reviewer can see at a glance that no previously pinned value moved.
    //
    // They exist because mutation-checking found the pin blind to all three. With only url,
    // headers and body captured, changing 'POST' to 'PUT', dropping the `stream` option, or
    // deleting the telemetry-correlation wrapper each left all 203 captures passing -- and all
    // three live in the single toHttpRequest() that BaseHttpRequestAdapter now shares across
    // every provider, which is precisely the blast radius this fixture exists to guard.
    return [
        'url' => $sent->url(),
        'headers' => $sent->headers(),
        'body' => json_last_error() === JSON_ERROR_NONE ? $decoded : $body,
        'method' => $sent->method(),
        'options' => $sent->options(),
        'telemetry' => $sent->metadata->get(HttpRequestTelemetry::CORRELATION_METADATA_KEY),
    ];
}

/** @return array<string,mixed> */
function driverGoldenCapabilities(string $providerName): array {
    $driver = BundledInferenceDrivers::registry()->makeDriver(
        $providerName,
        driverGoldenConfig($providerName),
        (new HttpClientBuilder())->withDriver(new MockHttpDriver())->create(),
        new EventDispatcher(),
    );

    if (!method_exists($driver, 'capabilities')) {
        return ['NO CAPABILITIES METHOD' => true];
    }

    $shape = static fn($caps): array => [
        'streaming' => $caps->supportsStreaming(),
        'toolCalling' => $caps->supportsToolCalling(),
        'toolChoice' => $caps->supportsToolChoice(),
        'jsonObject' => $caps->supportsResponseFormatJsonObject(),
        'jsonSchema' => $caps->supportsResponseFormatJsonSchema(),
        'formatWithTools' => $caps->supportsResponseFormatWithTools(),
        // No driver sets either of these today -- they are captured precisely because of
        // that. A spec that started populating them would otherwise change what every
        // caller of capabilities() sees without moving a single assertion.
        'maxContextTokens' => $caps->maxContextTokens,
        'maxOutputTokens' => $caps->maxOutputTokens,
    ];

    // Three model names, because at least one driver varies its answer by model
    // (Deepseek turns tools and schema off for its reasoner models). A single
    // capabilities() reading would pin only one side of that branch.
    return [
        'default' => $shape($driver->capabilities()),
        'test-model' => $shape($driver->capabilities('test-model')),
        'reasoner-model' => $shape($driver->capabilities('deepseek-reasoner')),
    ];
}

/** @return array<string,mixed> */
function driverGoldenSnapshot(): array {
    $out = [];
    foreach (BundledInferenceDrivers::registry()->driverNames() as $name) {
        $row = ['capabilities' => driverGoldenCapabilities($name)];
        foreach (driverGoldenRequests() as $variant => $request) {
            $row[$variant] = driverGoldenCapture($name, $request, str_ends_with($variant, '_streamed'));
        }
        $out[$name] = $row;
    }
    ksort($out);
    return $out;
}

/** @return array<string,mixed> */
function driverGoldenFixture(): array {
    return json_decode((string) file_get_contents(DRIVER_GOLDEN_FIXTURE), true, 512, JSON_THROW_ON_ERROR);
}

/**
 * Recursively sorts string-keyed arrays, leaving lists in their original order.
 *
 * Used only for the equivalence-class comparison, never for the byte-level fixture. Two
 * providers that emit the same headers in a different order, or the same body keys in a
 * different order, are the same request as far as any server is concerned -- and
 * `openai-responses` and `openresponses` differ in exactly that way and no other. Splitting
 * them apart would be a distinction the wire cannot see. List order IS preserved, because the
 * order of messages and tools is meaning, not formatting.
 */
function driverGoldenSortKeys(mixed $value): mixed {
    if (!is_array($value)) {
        return $value;
    }
    $value = array_map(driverGoldenSortKeys(...), $value);
    if (!array_is_list($value)) {
        ksort($value);
    }
    return $value;
}

/**
 * Groups providers by the whole of their captured output, so two providers land in the same
 * group exactly when they are indistinguishable on the wire across all seven requests.
 *
 * @param array<string,mixed> $snapshot
 * @return list<list<string>>
 */
function driverGoldenEquivalenceClasses(array $snapshot): array {
    $groups = [];
    foreach ($snapshot as $name => $row) {
        $requests = $row;
        unset($requests['capabilities']);
        $groups[md5((string) json_encode(driverGoldenSortKeys($requests)))][] = $name;
    }
    $classes = array_values($groups);
    foreach ($classes as &$members) {
        sort($members);
    }
    unset($members);
    usort($classes, static fn($a, $b) => $a[0] <=> $b[0]);
    return $classes;
}

it('emits the pinned HTTP request and capabilities for every bundled provider', function () {
    $snapshot = driverGoldenSnapshot();
    $fixture = driverGoldenFixture();

    // Not `expect($snapshot)->toBe($fixture)`, which is the same assertion but unusable when it
    // fails. The failure this fixture exists to catch is a change in the one toHttpRequest()
    // every provider shares, so it moves all 29 at once -- and asked to diff two 29-by-8 maps
    // of nested arrays, the renderer spent over two minutes without printing anything and had
    // to be killed. Measured, not guessed: that was the mutation that deleted the telemetry
    // wrapper from BaseHttpRequestAdapter.
    //
    // The drifted-key list is asserted FIRST on purpose. "all 29 providers, telemetry_correlated
    // only" is the diagnosis -- it says a shared path moved -- and it arrives in milliseconds.
    // The bounded value diff below then shows what actually changed, for one capture rather
    // than two hundred.
    $drifted = [];
    foreach ($fixture as $provider => $row) {
        foreach ($row as $variant => $capture) {
            if (($snapshot[$provider][$variant] ?? null) !== $capture) {
                $drifted[] = "{$provider}/{$variant}";
            }
        }
    }
    expect($drifted)->toBe([]);

    if ($drifted !== []) {
        [$provider, $variant] = explode('/', $drifted[0], 2);
        expect($snapshot[$provider][$variant] ?? null)->toBe($fixture[$provider][$variant]);
    }

    // A provider present in the snapshot but absent from the fixture is invisible to the loop
    // above, which walks the fixture.
    expect(array_keys($snapshot))->toBe(array_keys($fixture));
})->group('driver-golden');

it('covers every registry key, and the key set itself is pinned', function () {
    // The acceptance criterion for instructor-eexl.9 includes "the set of registry keys is
    // unchanged, including the four aliases". A driver silently dropped from the registry
    // would otherwise just shrink the comparison above and still pass.
    $names = BundledInferenceDrivers::registry()->driverNames();
    sort($names);
    $pinned = array_keys(driverGoldenFixture());
    sort($pinned);

    expect($names)->toBe($pinned)
        ->and($names)->toContain('moonshot', 'ollama', 'openai-compatible', 'together');
})->group('driver-golden');

it('keeps the wire-equivalence classes of the providers exactly as they are', function () {
    // THE FIXTURE'S BLIND SPOT, CLOSED. A refactor that collapsed several providers onto one
    // shared default AND regenerated the fixture would still satisfy the comparison above --
    // the fixture would simply record the collapsed behaviour as if it had always been so.
    //
    // This partition is therefore written out HERE, in the test source, not derived from the
    // fixture. It says which providers are byte-identical to each other on the wire and which
    // are not. Collapsing any two groups, or splitting any group, fails.
    //
    // Twenty-nine registry names, twenty-one wire-distinct behaviours. Read the multi-member
    // groups as the answer to "which drivers could share one spec": those six OpenAI-identical
    // providers already are identical, which is what makes the refactor safe, and the three
    // pairs below are the same claim in miniature.
    //
    // 'azure' and 'bedrock-openai' sit alone only because they rewrite the URL; their bodies
    // match the OpenAI group exactly. 'meta' is the deliberate near-miss -- identical to plain
    // OpenAI on six of the seven requests, differing only on json_object, which is precisely
    // why that variant was added. Under the original single-request fixture 'meta' fell into
    // the OpenAI group and its one real behaviour was unpinned.
    $pinned = [
        ['a21'],
        ['anthropic'],
        ['azure'],
        ['bedrock-openai'],
        ['cerebras'],
        ['cohere'],
        ['deepseek'],
        ['fireworks'],
        ['gemini'],
        ['gemini-oai', 'sambanova'],
        ['glm'],
        ['groq', 'openrouter'],
        ['huggingface'],
        ['inception', 'moonshot', 'ollama', 'openai', 'openai-compatible', 'together'],
        ['meta'],
        ['minimaxi'],
        ['mistral'],
        ['openai-responses', 'openresponses'],
        ['perplexity'],
        ['qwen'],
        ['xai'],
    ];
    foreach ($pinned as &$group) {
        sort($group);
    }
    unset($group);
    usort($pinned, static fn($a, $b) => $a[0] <=> $b[0]);

    expect(driverGoldenEquivalenceClasses(driverGoldenFixture()))->toBe($pinned);
})->group('driver-golden');
