driver: anthropic
apiUrl: 'https://api.anthropic.com/v1'
apiKey: '${ANTHROPIC_API_KEY}'
endpoint: /messages
metadata:
  apiVersion: '2023-06-01'
  beta: prompt-caching-2024-07-31
model: claude-haiku-4-5-20251001
maxTokens: 1024
contextLength: 200000
maxOutputLength: 8192
