driver: meta
apiUrl: 'https://openrouter.ai/api/v1'
apiKey: '${OPENROUTER_API_KEY}'
endpoint: /chat/completions
model: 'meta-llama/llama-3.3-8b-instruct:free'
maxTokens: 1024
contextLength: 128000
maxOutputLength: 8192
