driver: gemini-oai
apiUrl: 'https://generativelanguage.googleapis.com/v1beta/openai'
apiKey: '${GEMINI_API_KEY}'
endpoint: /chat/completions
model: gemini-2.5-flash-lite
maxTokens: 1024
contextLength: 1000000
maxOutputLength: 8192
