driver: sambanova
apiUrl: 'https://api.sambanova.ai/v1'
apiKey: '${SAMBANOVA_API_KEY}'
endpoint: /chat/completions
model: Meta-Llama-3.1-8B-Instruct
maxTokens: 1024
contextLength: 128000
maxOutputLength: 2048
