name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-24.04
    steps:
      - uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your pull request. However, you have submitted this PR on read-only sub split of `cognesy/instructor-php`. Please submit your PR on the https://github.com/cognesy/instructor-php repository.<br><br>Thanks!"