outputMode: tool_call
maxRetries: 0
useObjectReferences: false
schemaName: default_schema
schemaDescription: ''
toolName: extracted_data
toolDescription: 'Function call based on user instructions.'
defaultToStdClass: false
