<?php

declare(strict_types=1);

namespace Cognesy\Auxiliary\Beads\Domain\Model;

use Cognesy\Auxiliary\Beads\Domain\ValueObject\Agent;
use Cognesy\Auxiliary\Beads\Domain\ValueObject\TaskId;
use DateTimeImmutable;
use InvalidArgumentException;

/**
 * Comment Entity
 *
 * Represents a comment on a task. Immutable value object.
 */
final readonly class Comment
{
    /**
     * @param  int  $id  Comment ID (auto-generated by bd)
     * @param  TaskId  $taskId  Task this comment belongs to
     * @param  Agent  $author  Comment author
     * @param  string  $text  Comment text/message
     * @param  DateTimeImmutable  $createdAt  Creation timestamp
     * @param  array<string>  $mentions  Detected @mentions in text
     */
    public function __construct(
        public int $id,
        public TaskId $taskId,
        public Agent $author,
        public string $text,
        public DateTimeImmutable $createdAt,
        public array $mentions = [],
    ) {
        if ($id <= 0) {
            throw new InvalidArgumentException('Comment ID must be positive');
        }

        if (trim($text) === '') {
            throw new InvalidArgumentException('Comment text cannot be empty');
        }
    }

    /**
     * Create new comment (factory method)
     *
     * Auto-detects @mentions in text
     */
    public static function create(
        int $id,
        TaskId $taskId,
        Agent $author,
        string $text,
        ?DateTimeImmutable $createdAt = null,
    ): self {
        $mentions = self::detectMentions($text);

        return new self(
            id: $id,
            taskId: $taskId,
            author: $author,
            text: $text,
            createdAt: $createdAt ?? new DateTimeImmutable,
            mentions: $mentions,
        );
    }

    /**
     * Detect @mentions in text
     *
     * Matches patterns like @username or @"User Name"
     *
     * @return array<string>
     */
    private static function detectMentions(string $text): array
    {
        $mentions = [];

        // Match @username (alphanumeric + underscore + hyphen)
        preg_match_all('/@([a-zA-Z0-9_-]+)/', $text, $simpleMatches);
        $mentions = array_merge($mentions, $simpleMatches[1]);

        // Match @"User Name" (quoted mentions with spaces)
        preg_match_all('/@"([^"]+)"/', $text, $quotedMatches);
        $mentions = array_merge($mentions, $quotedMatches[1]);

        // Remove duplicates and return
        return array_values(array_unique($mentions));
    }

    /**
     * Check if comment mentions specific agent
     */
    public function mentions(Agent $agent): bool
    {
        return in_array($agent->id, $this->mentions, true)
            || ($agent->name !== null && in_array($agent->name, $this->mentions, true));
    }

    /**
     * Check if comment has any mentions
     */
    public function hasMentions(): bool
    {
        return count($this->mentions) > 0;
    }

    /**
     * Get comment age (duration since creation)
     */
    public function age(): \DateInterval
    {
        return $this->createdAt->diff(new DateTimeImmutable);
    }

    /**
     * Check if comment is authored by specific agent
     */
    public function isAuthoredBy(Agent $agent): bool
    {
        return $this->author->equals($agent);
    }

    /**
     * String representation
     */
    public function __toString(): string
    {
        return "{$this->author->displayName()}: {$this->text}";
    }
}
