templateEngine: twig
resourcePath: prompts/demo-twig
cachePath: /tmp/instructor/cache/twig
extension: .twig
frontMatterTags:
  - '{#---'
  - '---#}'
frontMatterFormat: yaml
metadata:
  autoReload: true
