<?php

return [
    'defaultPreset' => 'curl',

    'presets' => [
        'curl' => [
            'driver' => 'curl',
            'connectTimeout' => 5,
            'requestTimeout' => 60,
            'idleTimeout' => -1,
            'streamChunkSize' => 256,
            'maxConcurrent' => 5,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
        'guzzle' => [
            'driver' => 'guzzle',
            'connectTimeout' => 3,
            'requestTimeout' => 30,
            'idleTimeout' => -1,
            'streamChunkSize' => 256,
            'maxConcurrent' => 5,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
        'symfony' => [
            'driver' => 'symfony',
            'connectTimeout' => 10,
            'requestTimeout' => 30,
            'idleTimeout' => -1,
            'streamChunkSize' => 0,
            'maxConcurrent' => 5,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
        'laravel' => [
            'driver' => 'laravel',
            'connectTimeout' => 3,
            'requestTimeout' => 30,
            'idleTimeout' => -1,
            'streamChunkSize' => 256,
            'maxConcurrent' => 5,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
        'exthttp' => [
            'driver' => 'exthttp',
            'connectTimeout' => 3,
            'requestTimeout' => 30,
            'idleTimeout' => -1,
            'streamChunkSize' => 256,
            'maxConcurrent' => 10,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
        'http-ollama' => [
            'driver' => 'guzzle',
            'connectTimeout' => 3,
            'requestTimeout' => 90,
            'streamChunkSize' => 256,
            'idleTimeout' => -1,
            'maxConcurrent' => 5,
            'poolTimeout' => 60,
            'failOnError' => false,
        ],
    ],
];
