name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: 'PHP ${{ matrix.php }} (Symfony ${{ matrix.symfony }}, Composer Flags: ${{ matrix.composer }})'

    runs-on: ubuntu-24.04

    strategy:
      fail-fast: true
      matrix:
        php: ['8.3', '8.4', '8.5']
        symfony: ['^7.0', '^8.0']
        composer: ['--prefer-stable', '--prefer-lowest']
        exclude:
          - php: '8.3'
            symfony: '^8.0'

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

#    - name: Cache Composer packages
#      id: composer-cache
#      uses: actions/cache@v3
#      with:
#        path: vendor
#        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#        restore-keys: |
#          ${{ runner.os }}-php-

    - name: Install dependencies
      run: >
        composer update --no-interaction ${{ matrix.composer }} -W
        --with symfony/console:${{ matrix.symfony }}
        --with symfony/filesystem:${{ matrix.symfony }}
        --with symfony/process:${{ matrix.symfony }}
        --with symfony/property-access:${{ matrix.symfony }}
        --with symfony/property-info:${{ matrix.symfony }}
        --with symfony/serializer:${{ matrix.symfony }}
        --with symfony/validator:${{ matrix.symfony }}
        --with symfony/var-dumper:${{ matrix.symfony }}
        --with symfony/yaml:${{ matrix.symfony }}
        --with symfony/css-selector:${{ matrix.symfony }}
        --with symfony/dom-crawler:${{ matrix.symfony }}
        --with symfony/http-client:${{ matrix.symfony }}

    - name: Regenerate Autoloader
      run: composer dump-autoload

    - name: Run test suite (all code local)
      run: composer test

    - name: Run Instructor docs QA
      run: composer --working-dir=packages/instructor docs:qa

#    - name: Install dependencies in all packages
#      run: |
#        for dir in packages/*; do
#          if [ -f "$dir/composer.json" ]; then
#            echo "📦 Installing dependencies in $dir"
#            composer --working-dir="$dir" update --no-interaction ${{ matrix.composer }}
#          fi
#        done

#    - name: Run all tests
#      run: ./bin/run-all-tests.sh
